angular
		.module("prostudyApp")
		.controller(
				"schoolRegisterAddCtr",
				function($scope, $window, $mdToast, $timeout, $mdSidenav,
						$mdUtil, $log, $q, tableTestDataFactory, $state,
						$stateParams, $location, $anchorScroll, appEndpointSF,
						partnerSchoolLevels, standardList,
						indiaAddressLookupData) {

					console.log("Inside schoolRegisterAddCtr");
					$scope.curUser = appEndpointSF.getLocalUserService()
							.getLoggedinUser();

					$scope.Country = indiaAddressLookupData;
					$scope.partnerSchoolLevels = partnerSchoolLevels;
					$scope.standardList = standardList;

					$scope.partnerSchool = {
						address : $scope.Address,
						autoGenerated : "",
						govRegisterno : "",
						schoolName : "",
						instName : "",
						formNumber : "",
						category : "",
						contactDetail : "",
						primaryContact : "",

					};

					$scope.contactDetail = {
						headMasterName : "",
						headMasterMobile : "",
						headMasterPhone : "",
						headMasterEmailId : "",
						coordinatorDetail : [ {
							srno : 1,
							coordinatorName : "",
							coordinatorPhoneNum : "",
							coordinatorMobileNum : "",
							coordinatorEmailId : "",
						} ]

					}

					$scope.addPartnerSchool = function() {

						// $scope.partnerSchool.instituteID =
						// $scope.curUser.instituteID;
						$scope.partnerSchool.contactDetail = $scope.contactDetail;

						if ($scope.schoolid != undefined
								&& $scope.selectedPSchoolId == "") {
							$scope.partnerSchool.id = $scope.schoolid.id;
						}

						if ($scope.partnerSchool.address.state == "Other") {
							$scope.partnerSchool.address.state = $scope.partnerSchool.address.otherState;
							$scope.partnerSchool.address.dist = $scope.partnerSchool.address.otherDist;
							$scope.partnerSchool.address.tal = $scope.partnerSchool.address.otherTaluka;
							$scope.partnerSchool.address.otherAddressFlag = true;
						} else {
							$scope.partnerSchool.address.otherAddressFlag = false;
						}
						var PartnerSchoolService = appEndpointSF
								.getPartnerSchoolService();

						$scope.partnerSchool.modifiedDate = new Date();
						// $scope.partnerSchool.modifiedBy =
						// $scope.curUser.email_id;

						$location.hash('topRight');
						$anchorScroll();
						$scope.loading = true;

						var UserService = appEndpointSF.getUserService();
						UserService
								.getUserByEmailID('guest@system.com')
								.then(
										function(foundUser) {

											$scope.partnerSchool.instituteID = foundUser.instituteID
											PartnerSchoolService
													.addPartnerSchool(
															$scope.partnerSchool)
													.then(
															function(schoolid) {
																$scope.loading = false;
																if (schoolid.code) {
																	$scope
																			.showErrorToast("Error occured while saving data. Please try latter on or contact technical support. Error Details:"
																					+ schoolid.message);
																} else {
																	$scope.schoolid = schoolid;
																	$scope.partnerSchool.autoGenerated = $scope.schoolid.autoGenerated;

																	if ($scope.selectedPSchoolId != undefined) {
																		$scope
																				.showUpdateToast();
																	} else {
																		$scope
																				.showAddToast();
																	}
																	$scope.addPaymentFlag = false;
																	$location
																			.hash('topRight');
																	$anchorScroll();
																}

															});

											$scope.partnerSchool = $scope
													.clearData();

										});

					}

					$scope.clearData = function() {

						return {
							address : $scope.Address,
							autoGenerated : "",
							govRegisterno : "",
							instituteID : "",
							schoolName : "",
							instName : "",
							formNumber : "",
							category : "",
						}

					}

					$scope.temp = {
						tempDistricts : [],
						tempTalukas : [],
						tempVillages : []
					}

					$scope.getDistricts = function(index, state) {

						$scope.temp.tempDistricts = [];
						for (var i = 0; i < $scope.Country.states.length; i++) {

							if ($scope.Country.states[i].name == state) {
								$scope.temp.tempDistricts = $scope.Country.states[i].districts;
							}
						}
					};

					$scope.getTalukas = function(index, district) {

						$scope.temp.tempTalukas = [];
						for (var j = 0; j < $scope.temp.tempDistricts.length; j++) {
							if ($scope.temp.tempDistricts[j].name == district) {
								$scope.temp.tempTalukas = $scope.temp.tempDistricts[j].talukas;
							}
						}
					};

					$scope.getVillages = function(index, taluka) {

						$scope.temp.tempVillages = [];
						for (var k = 0; k < $scope.temp.tempTalukas.length; k++) {
							if ($scope.temp.tempTalukas[k].name == taluka) {
								$scope.temp.tempVillages = $scope.temp.tempTalukas[k].villages;
							}
						}
					};
				});