<html>
<h2 style="color:Chocolate;" align="center">Gandhi Vichar Sanskar Pariksha</h2>
<p align="center">Address :- Gandhi Teerth, Jain Hills,, Jalgaon, Maharashtra 425003</p>
<hr style="color:RoyalBlue";></hr>
<br></br>
<h3 style="color:red;" align="center">Certificate</h3>
<br></br>
<div align="left">
<h4 align="center">Mr./Miss. ${studName}</h4>
is here by awarded this certificate of achievement for the sucessful completion of the GVSP Exam ${date} for the Standard ${studStandard}.
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<hr style="color:RoyalBlue";></hr>
<div align="left">
<p><span style="color:SeaGreen;">Gandhi Research Foundation</span>&nbsp;&nbsp;&nbsp;   +91 257 2260033, 2264801, info@gandhifoundation.net</p>  
<!--<p>Contact : +91 257 2260033, 2264801&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email: info@gandhifoundation.net </p>-->
</div>
</html>