<html>
  <p>Dear ${firstName} Sir,</p>
  <p>You school/college has been registered for Gandhi Research Foundation Exam for year 2016-17. Please see details below. Thank you.</p>
  <p>Total number of students participating in exam: ${totalStudents}</p>
  <p>Boys: ${totalBoys}</p>
  <p>Girls: ${totalGirls}</p>
  <br>
  <p>Thanks and Regards</p>  
  <p>Gandhi Vichar Sanskar Pariksha,</p>
  <p>Gandhi Research Foundation,</p>
  <p>Gandhi Teerth, Jain Hills, Jalgaon, Maharashtra-425003</p>
  <p>email: gandhiexam@gandhifoundation.net</p>
  <p>website: http://www.gandhifoundation.net</p>
</html>