package com.protostar.prostudy.gf.service;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.protostar.prostudy.entity.Address;
import com.protostar.prostudy.gf.entity.BookDetail;
import com.protostar.prostudy.gf.entity.BookSummary;
import com.protostar.prostudy.gf.entity.ExamDetail;
import com.protostar.prostudy.gf.entity.GFBookEntity;
import com.protostar.prostudy.gf.entity.PartnerSchoolEntity;
import com.protostar.prostudy.gf.entity.PaymentDetail;

public class DownloadBookDetailsReport extends HttpServlet {
	private static final long serialVersionUID = 1L;

	public DownloadBookDetailsReport() {
		super();
		// TODO Auto-generated constructor stub
	}

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		if (request.getRemoteHost().contains("localhost")
				|| request.getRemoteHost().contains("127.0.0.1")) {
			response.addHeader("Access-Control-Allow-Origin", "*");
			response.addHeader("Access-Control-Allow-Methods",
					"GET,PUT,POST,DELETE");
			response.addHeader("Access-Control-Allow-Headers", "Content-Type");
		}

		Long schoolId = Long.parseLong(request.getParameter("schoolId"));
		String yearOfExam = request.getParameter("yearOfExam");
		String paymentType = request.getParameter("paymentType");
		
		int totalStudent = 0, tempBookAmt = 0, tempGRFAmt = 0;
		float totalBookAmount = 0.0f, totalGRFFees = 0.0f, bookAmt20per = 0.0f, bookAmt80per = 0.0f, examAmt20per = 0.0f, examAmt80per = 0.0f;
		Date date = new Date();
		String DATE_FORMAT = "dd/MM/yyyy";
		SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
		sdf.setTimeZone(TimeZone.getTimeZone("IST"));

		PartnerSchoolService pschoolService = new PartnerSchoolService();
		PartnerSchoolEntity schoolEntity = pschoolService
				.getPSchoolByPSID(schoolId);
		List<PaymentDetail> paymentDetailList = new ArrayList<PaymentDetail>();

		try {

			response.setContentType("text/csv");

			response.setHeader(
					"Content-Disposition",
					"attachment; filename=BookDetailsReport_"
							+ sdf.format(date) + ".csv");
			
			ServletOutputStream outputStream = response.getOutputStream();
			OutputStreamWriter writer = new OutputStreamWriter(outputStream);
			
			writer.append(",");
			writer.append("Gandhi Research Foundation");
			writer.append(",");
			writer.append(System.lineSeparator());
			
			writer.append(",");
			writer.append("Gandhi Vichar Sanskar Pariksha "+yearOfExam+" "+paymentType+" "+"Format");
			writer.append(',');
			writer.append(',');
			writer.append(System.lineSeparator());
			
			writer.append("Reg. No.");
			writer.append(',');
			writer.append(schoolEntity.getAutoGenerated());
			writer.append(',');
			writer.append(System.lineSeparator());
			
			writer.append("School Name");
			writer.append(',');
			writer.append(schoolEntity.getSchoolName());
			writer.append(',');
			writer.append(System.lineSeparator());
			
			writer.append("Address");
			writer.append(',');
			Address address = schoolEntity.getAddress();
			writer.append("At."+address.getCity());
			writer.append(',');
			writer.append(System.lineSeparator());
			
			writer.append("Standard");
			writer.append(',');
			writer.append("Book Name");
			writer.append(',');
			writer.append("Qty.");
			writer.append(',');
			writer.append("Book Price");
			writer.append(',');
			writer.append("Book Amount");
			writer.append(',');
			writer.append("Total Offer");
			writer.append(',');
			writer.append("GRF Total");
			writer.append(',');

			writer.append(System.lineSeparator());

			List<ExamDetail> examDetailList = schoolEntity.getExamDetailList();
			for (int j = 0; j < examDetailList.size(); j++) {
				if (examDetailList != null
						&& examDetailList.size() > 0
						&& examDetailList.get(j).getYearOfExam().trim()
								.equalsIgnoreCase(yearOfExam.trim())) {
					
					BookSummary bookSummary = examDetailList.get(j)
							.getBookSummary();
					paymentDetailList = examDetailList.get(j).getPaymentDetail();
					if (bookSummary != null) {
						
						List<BookDetail> bookDetail = bookSummary
								.getBookDetail();
						if (bookDetail != null && bookDetail.size() > 0) {
							for (BookDetail book : bookDetail) {
								if (book.getBookName() != null) {
									
									GFBookStockService bookService = new GFBookStockService();
									GFBookEntity bookEntity = bookService
											.getGFBookById(Long.parseLong(book
													.getBookName().trim()));
									writer.append(book.getStandard());
									writer.append(',');
									String bookName = " "+ "("+ bookEntity.getStandard()+ '-'+ bookEntity.getBookMedium()+ ")";
									writer.append(bookEntity.getBookName()
											.concat(bookName));
									writer.append(',');
									totalStudent += book.getTotalStud();
									writer.append(book.getTotalStud()
											.toString());
									writer.append(',');
									writer.append(book.getBookPrise()
											.toString());
									writer.append(',');
									tempBookAmt += book.getTotalFees();
									totalBookAmount = (float)tempBookAmt;
									writer.append(book.getTotalFees()
											.toString());
									writer.append(',');
									writer.append(book.getExamFees().toString());
									writer.append(',');
									tempGRFAmt += book.getTotalExamFees();
									totalGRFFees = (float)tempGRFAmt;
									writer.append(book.getTotalExamFees()
											.toString());
									writer.append(',');
									writer.append(System.lineSeparator());
								}
							}
						}
					}
				}
			}
			
			bookAmt20per += Math.round(((totalBookAmount / 100) * 20));
			bookAmt80per += Math.round(((totalBookAmount / 100) * 80));
			
			examAmt20per += Math.round(((totalGRFFees / 100) * 20));
			examAmt80per += Math.round(((totalGRFFees / 100) * 80));

			writer.append(',');
			writer.append("Total A");
			writer.append(',');
			writer.append(Integer.toString(totalStudent));
			writer.append(',');
			writer.append(',');
			writer.append(String.valueOf(totalBookAmount));
			writer.append(',');
			writer.append(',');
			writer.append(String.valueOf(totalGRFFees));
			writer.append(',');
			writer.append(System.lineSeparator());
			
			writer.append(',');
			writer.append("20% Expensess");
			writer.append(',');
			writer.append(',');
			writer.append(',');
			writer.append(String.valueOf(bookAmt20per));
			writer.append(',');
			writer.append(',');
			writer.append(String.valueOf(examAmt20per));
			writer.append(System.lineSeparator());

			writer.append(',');
			writer.append("Grand Total");
			writer.append(',');
			writer.append(',');
			writer.append(',');
			writer.append(String.valueOf(bookAmt80per));
			writer.append(',');
			writer.append(',');
			writer.append(String.valueOf(examAmt80per));
			writer.append(System.lineSeparator());
			
			if (paymentDetailList != null && paymentDetailList.size() > 0){
				for (PaymentDetail payment : paymentDetailList) {
					if(payment.getPayReceivedBy().trim().equalsIgnoreCase("D.D")){
						writer.append("D.D No.");
						writer.append(',');
						String ddNo = payment.getTransactionNumber();
						writer.append(ddNo);
						writer.append(',');
						writer.append(System.lineSeparator());
						
						writer.append("Bank Name");
						writer.append(',');
						writer.append(payment.getDdBankName());
						writer.append(',');
						writer.append(System.lineSeparator());
						
						writer.append("Branch");
						writer.append(',');
						writer.append(payment.getDdBranchName());
						writer.append(',');
						writer.append(System.lineSeparator());
						
						writer.append("D.D Date");
						writer.append(',');
						Date tempDDDate = payment.getDdCreatedDate();
						String ddDate = sdf.format(tempDDDate);
						writer.append(ddDate);
						writer.append(',');
						writer.append(System.lineSeparator());
					}
					writer.append("Deposit in");
					writer.append(',');
					String bankName = payment.getNameOfBank();
					writer.append(bankName);
					writer.append(',');
					writer.append(System.lineSeparator());
					
					writer.append("Branch");
					writer.append(',');
					String branch = payment.getBranchName();
					writer.append(branch);
					writer.append(',');
					writer.append(System.lineSeparator());
					
					writer.append("Amt. Rs.");
					writer.append(',');
					String payAmount = String.valueOf(payment.getPayAmount());
					writer.append(payAmount);
					writer.append(',');
					writer.append(System.lineSeparator());
					
					writer.append("Deposit Date");
					writer.append(',');
					Date tempDepositDate = payment.getDepositDate();
					String depositDate = sdf.format(tempDepositDate);
					writer.append(depositDate);
					writer.append(',');
				}
			}

			writer.close();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

}
