import { Component, Optional, OnInit } from '@angular/core';
import { MdDialog, MdDialogRef, MdSnackBar } from '@angular/material';
import { Router, ActivatedRoute, Params } from '@angular/router';

import { courierTypelist, logisticsList } from '../core/constant.app';
import { PartnerSchool } from '../partnerschool/partner-school';
import { CourierSerivces, GFCourier } from './courier.service';

import { RouteData } from '../route-data.provider';

@Component({
    moduleId: module.id,
    selector: 'proerp-add-courier',
    templateUrl: './add-courier.component.html',
    styleUrls: ['./feature.component.css']
})

export class AddCourierComponent implements OnInit {

    id: string;
    tempCourierObj: GFCourier;
    name: string;
    phone1: string;
    phone2: string;
    cost: number;
    docketID: string;
    note: string;
    courierDispatchDate: any;
    courierTypelist: string[];
    logisticsList: string[];

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private routeData: RouteData,
        private courierservice: CourierSerivces
    ) {
        this.courierTypelist = courierTypelist;
        this.logisticsList = logisticsList;
        console.log("inside add courier page");
        this.tempCourierObj = {
            id: '',
            instituteID: 5910974510923776,
            autoGenerated: '',
            courierCost: 0,
            courierDocketID: '',
            courierName: '',
            courierPhone1: '',
            courierPhone2: '',
            courierType: '',
            logistics: '',
            totalWeight: 0,
            courierFrom: '',
            courierTo: '',
            schoolName: new PartnerSchool(),
            totalFees: 0,
            courierDispatchDate: new Date(),
            bookQty: 0,
            bookLineItemList: [],
            courierDispatchNotes: ''
        };
    }

    ngOnInit() {
        if (this.routeData.params.selectedCourierID) {
            this.id = this.routeData.params.selectedCourierID;
            this.getGFCourierById(this.id);
            console.log('this.user.id: ' + this.id);
            // Clean the data from routeData 
            this.routeData.params.selectedCourierID = null;
        }
    }

    addCourier() {
        if (this.tempCourierObj.id) {
            this.tempCourierObj.courierName = this.name;
            this.tempCourierObj.courierDocketID = this.docketID;
            this.tempCourierObj.courierPhone1 = this.phone1;
            this.tempCourierObj.courierPhone2 = this.phone2;
            this.tempCourierObj.courierCost = this.cost;
            this.tempCourierObj.courierDispatchNotes = this.note;
            this.tempCourierObj.courierDispatchDate = this.courierDispatchDate;
        }
        this.courierservice.addCourier(this.tempCourierObj).then(courierObj => {
            console.log('Saved currentSchool:' + courierObj);
            this.tempCourierObj = courierObj;
            if (this.tempCourierObj) {
                this.router.navigate(['/courier-index/listcourier']);
            }
        });
    }

    getGFCourierById(id: string) {
        this.courierservice.getGFCourierById(id).then(list => {
            this.tempCourierObj = list;
            this.name = this.tempCourierObj.courierName;
            this.docketID = this.tempCourierObj.courierDocketID;
            this.phone1 = this.tempCourierObj.courierPhone1;
            this.phone2 = this.tempCourierObj.courierPhone2;
            this.cost = this.tempCourierObj.courierCost;
            this.note = this.tempCourierObj.courierDispatchNotes;
            this.courierDispatchDate = this.tempCourierObj.courierDispatchDate;
        });
    }

    gotolistCourier(){
         this.router.navigate(['/courier-index/listcourier']);
    }
}