package com.protostar.prostudy.gf.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.googlecode.objectify.Ref;
import com.googlecode.objectify.annotation.Cache;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Index;
import com.googlecode.objectify.annotation.OnSave;
import com.protostar.prostudy.entity.Address;
import com.protostar.prostudy.entity.BaseEntity;

@Entity
@Cache
public class PartnerSchoolEntity extends BaseEntity {

	@Index
	private ContactDetail contactDetail;

	@Index
	private Address address;

	@Index
	private Long instituteID;

	private String schoolName;

	@Index
	private String[] schoolNameIndex;
	
	@Index
	private String[] examDetailIndex;

	private String instName;

	@Index
	private String formNumber;

	private String category;
	private String primaryContact;

	@Index
	private String autoGenerated;

	private String govRegisterno;

	@Index
	private Date lastModifiedDate;

	@Index
	private boolean schoolSelfUpdate = false;
	
	@Index
	private Ref<PartnerSchoolInstituteEntity> schoolInstitute;

	public boolean isSchoolSelfUpdate() {
		return schoolSelfUpdate;
	}

	public void setSchoolSelfUpdate(boolean schoolSelfUpdate) {
		this.schoolSelfUpdate = schoolSelfUpdate;
	}

	private List<ExamDetail> examDetailList = new ArrayList<ExamDetail>();

	@OnSave
	public void createSchoolNameIndex() {
		schoolNameIndex = schoolName.trim().split(" ");
		examDetailIndex = getExamDetailListIndex();
	}

	private String[] getExamDetailListIndex() {
		List<ExamDetail> examDetailList = getExamDetailList();
		List<String> indexList = new ArrayList<String>();
		for (ExamDetail examDetail : examDetailList) {
			indexList.add(examDetail.getYearOfExam());
		}
		String[] array = indexList.toArray(new String[0]);
		return array;
	}

	public Long getInstituteID() {
		return instituteID;
	}

	public void setInstituteID(Long instituteID) {
		this.instituteID = instituteID;
	}

	public String getFormNumber() {
		return formNumber;
	}

	public void setFormNumber(String formNumber) {
		this.formNumber = formNumber;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getPrimaryContact() {
		return primaryContact;
	}

	public void setPrimaryContact(String primaryContact) {
		this.primaryContact = primaryContact;
	}

	public String getSchoolName() {
		return schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	public ContactDetail getContactDetail() {
		return contactDetail;
	}

	public void setContactDetail(ContactDetail contactDetail) {
		this.contactDetail = contactDetail;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(String autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

	public String getGovRegisterno() {
		return govRegisterno;
	}

	public void setGovRegisterno(String govRegisterno) {
		this.govRegisterno = govRegisterno;
	}

	public String getInstName() {
		return instName;
	}

	public void setInstName(String instName) {
		this.instName = instName;
	}

	public List<ExamDetail> getExamDetailList() {
		return examDetailList;
	}

	public void setExamDetailList(List<ExamDetail> examDetailList) {
		this.examDetailList = examDetailList;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public String[] getSchoolNameIndex() {
		return schoolNameIndex;
	}

	public void setSchoolNameIndex(String[] schoolNameIndex) {
		this.schoolNameIndex = schoolNameIndex;
	}

	public String[] getExamDetailIndex() {
		return examDetailIndex;
	}

	public void setExamDetailIndex(String[] examDetailIndex) {
		this.examDetailIndex = examDetailIndex;
	}

	public PartnerSchoolInstituteEntity getSchoolInstitute() {
		return schoolInstitute == null ? null : schoolInstitute.get();
	}

	public void setSchoolInstitute(PartnerSchoolInstituteEntity schoolInstitute) {
		this.schoolInstitute = Ref.create(schoolInstitute);
	}

}// end of PartnerSchoolEntity