export class PartnerSchool {
    id: string;
    schoolName:string;
    instName:string;
    formNumber:string;
    category:string;
    primaryContact:string;
    autoGenerated:string;
    govRegisterno:string;
    instituteID: number = +'5910974510923776';
    address:Address = new Address();
    contactDetail:ContactDetail = new ContactDetail();
    examDetailList:Array<ExamDetail>;
}

export class Address {
  line1:string;
  line2:string;
  city:string;
  state:string;
  pin:string;
}

export class ContactDetail {
    headMasterName:string;
    headMasterMobile:string;
    headMasterPhone:string;
    headMasterEmailId:string;
    coordinatorDetail:Array<CoordinatorDetail>;
}

export class CoordinatorDetail {
    srno:number=1;
    coordinatorName:string;
    coordinatorPhoneNum:string;
    coordinatorEmailId:string;
    coordinatorMobileNum:string;
}

export class ExamDetail {
    totalStudent:string;
    male:string;
    female:string;
    total:string;
    yearOfExam:string;
    bookRequired:string;
    modeOfExam:string;
    bookSummary:BookSummary = new BookSummary();
    paymentDetail:Array<PaymentDetail>;
}

export class BookSummary {
    total:number;
    appearedSchoolTotalStud:number = 0;
    amtForInst20per:number;
    amtForGRF80per:number;
    bookDetail:Array<BookDetail>;
}

export class BookDetail {
    bookName:string;
    bookPrise:number;
    standard:string;
    totalStud:number;
    appearedTotalStud:number = 0;
    totalFees:number;
}

export class PaymentDetail {
    payReceivedBy:string;
    paymentDate:Date = new Date();
    payAmount:number;
    tPaid:number;
    pAmount:number;
    note:string;
    nameOfBank:string;
    branchName:string;
    transactionNumber:string;
    depositDate:Date = new Date();
}