package com.protostar.prostudy.gf.service;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.protostar.prostudy.gf.entity.GFExamResultEntity;
import com.protostar.prostudy.gf.entity.PartnerSchoolEntity;

/**
 * Servlet implementation class DownloadExamResultReport
 */
public class DownloadExamResultReport extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public DownloadExamResultReport() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		String standard=request.getParameter("examResultByStandard");
				
		String district=request.getParameter("examResultByDistrict");
		
		String DATE_FORMAT = "dd-MM-yyyy";
		SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
		
		
		GFStudentService gfStudentServices=new GFStudentService();
		
		List<GFExamResultEntity> gfExamResultData = gfStudentServices.filterExamResults(standard,district);
		
		
		try {
			
			response.setContentType("text/csv");
			response.setHeader("Content-Disposition",
					"attachment; filename=ExamResultCSVData_"+sdf.format(new Date())+".csv");
			
			ServletOutputStream outputStream = response.getOutputStream();
			OutputStreamWriter writer = new OutputStreamWriter(outputStream);
			
			writer.append("Standard");
			writer.append(',');
			writer.append("Marks");
			writer.append(',');
			writer.append("Student Name");
			writer.append(',');
			writer.append("GRF.Reg.no");
			writer.append(',');
			writer.append("School Name");
			writer.append(',');
			writer.append("District");
			writer.append(',');
			
			writer.append(System.lineSeparator());
			
			for (int i = 0; i < gfExamResultData.size(); i++) {
								
				GFExamResultEntity examResultEntity = gfExamResultData.get(i);
				String Standard = examResultEntity.getStandard();
				writer.append(Standard);
				writer.append(',');
				float studMarks = examResultEntity.getMarks();
				String marks = Float.toString(studMarks);
				writer.append(marks);
				writer.append(',');
				String studName = examResultEntity.getStudName();
				writer.append(studName);
				writer.append(',');
				String grfRegNo=examResultEntity.getSchool().getAutoGenerated();
				writer.append(grfRegNo);
				writer.append(',');
				String schoolName=examResultEntity.getSchool().getSchoolName();
				writer.append(schoolName);
				writer.append(',');
				String studdistrict=examResultEntity.getSchool().getAddress().getDist();
				writer.append(studdistrict);
				writer.append(',');
				
				writer.append(System.lineSeparator());
				
			}
			
			writer.close();
							
		} catch (Exception e) {
			// TODO: handle exception
			throw new ServletException("Exception in Excel Sample Servlet", e);
		}
		
	}

}	
