package com.protostar.prostudy.gf.service;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.fileupload.FileItemIterator;
import org.apache.commons.fileupload.FileItemStream;
import org.apache.commons.fileupload.servlet.ServletFileUpload;

import com.protostar.prostudy.entity.Address;
import com.protostar.prostudy.gf.entity.ContactDetail;
import com.protostar.prostudy.gf.entity.CoordinatorDetail;
import com.protostar.prostudy.gf.entity.ExamDetail;
import com.protostar.prostudy.gf.entity.PartnerSchoolEntity;
import com.protostar.prostudy.until.data.UtilityService;

/**
 * Servlet implementation class UplodePartnerSchoolsExcel
 */
public class UplodePartnerSchoolsExcel extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private final Logger log = Logger.getLogger(UplodePartnerSchoolsExcel.class
			.getName());

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public UplodePartnerSchoolsExcel() {
		super();
		// TODO Auto-generated constructor stub
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		log.info("In side UplodePartnerSchoolsExcel");
		this.doGet(request, response);
	}

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		try {
			if (request.getHeader("Content-Type") != null
					&& request.getHeader("Content-Type").startsWith(
							"multipart/form-data")) {
				ServletFileUpload upload = new ServletFileUpload();

				FileItemIterator iterator = upload.getItemIterator(request);
				String[] split2 = null;
				Map parameterMap = request.getParameterMap();
				for (Object key : parameterMap.keySet()) {
					log.fine("key:" + key + "\b value:" + parameterMap.get(key));
				}

				Long insId = 0L;
				while (iterator.hasNext()) {
					FileItemStream item = iterator.next();
					log.fine("item.getFieldName(): " + item.getFieldName());

					if (item.getName() == null) {
						// It is form field not file.

						if ("instituteId".equalsIgnoreCase(item.getFieldName())) {
							insId = Long.parseLong(UtilityService.read(item
									.openStream()));

						}
						continue;
					}
					InputStream openStream = item.openStream();
					int len = 0;
					byte[] fileContent = new byte[20000000];
					// Can handle files upto 20 MB

					int read = openStream.read(fileContent);
					// log.fine("No of bytes read:" + read);
					int noCharsRead = 0;
					while (len != -1) {
						len = openStream.read(fileContent, noCharsRead == 0 ? 0
								: noCharsRead - 1, fileContent.length
								- noCharsRead);
						noCharsRead += len;
					}
					log.info("noCharsRead : " + noCharsRead);
					// log.info("File content is : " + new String(fileContent));
					log.info("File Read is Done!!");
					// Write code here to parse sheet of patients and upload to
					// database

					String fileAsString = new String(fileContent);

					split2 = fileAsString.split("\n");

				}
				// gte business entity
				System.out.println("No of records to process: "  + split2.length);				

				for (int row = 1; row < split2.length; row++) {
					try {
						String[] split = split2[row].split(",");
						if (split == null || split.length < 18) {
							continue;
						}

						// insert partner school
						PartnerSchoolEntity patschool = new PartnerSchoolEntity();
						patschool.setAutoGenerated(split[0]);
						patschool.setSchoolName(split[1]);
						patschool.setInstName(split[2]);
						patschool.setFormNumber(split[3]);
						patschool.setCategory(split[4]);
						/* patschool.setPrimaryContact(split[4]); */
						patschool.setInstituteID(insId);
						// address
						Address add = new Address();
						add.setLine1(split[5]);
						add.setLine2(split[6]);
						add.setCity(split[7]);
						add.setTal(split[8]);
						add.setDist(split[9]);
						add.setState(split[10]);
						add.setCountry(split[11]);
						add.setPin(split[12]);
						patschool.setAddress(add);

						// Contact Detail
						ContactDetail conDetail = new ContactDetail();

						conDetail.setHeadMasterName(split[13]);
						conDetail.setHeadMasterMobile(split[14]);
						conDetail.setHeadMasterEmailId(split[15]);
						patschool.setContactDetail(conDetail);

						CoordinatorDetail corddetail = new CoordinatorDetail();
						corddetail.setCoordinatorName(split[16]);
						corddetail.setCoordinatorMobileNum(split[17]);
						corddetail.setCoordinatorEmailId(split[18]);

						List<CoordinatorDetail> corddetailList = new ArrayList<CoordinatorDetail>();
						corddetailList.add(corddetail);
						conDetail.setCoordinatorDetail(corddetailList);

						/*
						 * corddetail.setSrno(1);
						 * corddetail.setCoordinatorEmailId(split[26]);
						 * corddetail.setCoordinatorName(split[24]);
						 * corddetail.setCoordinatorPhoneNum(split[25]);
						 * 
						 * conDetail.setCoordinatorDetail(Arrays
						 * .asList(corddetail));
						 */

						// ExamDetail
						ExamDetail eDtail = new ExamDetail();
						/*
						 * eDtail.setBookRequired(split[19]);
						 *//*
							 * eDtail.setExamMedium(Arrays.asList(split[15],
							 * split[16], split[17]));
							 */
						eDtail.setFemale("");
						eDtail.setMale("");
						eDtail.setModeOfExam("");
						eDtail.setTotal("");
						eDtail.setTotalStudent("");
						eDtail.setYearOfExam(split[19]);

						List<ExamDetail> examList = new ArrayList<ExamDetail>();
						examList.add(eDtail);
						patschool.setExamDetailList(examList);

						// book summary
						// BookSummary bookSummary = new BookSummary();
						/* patschool.setBookSummary(bookSummary); */

						PartnerSchoolService partnerSchool = new PartnerSchoolService();
						partnerSchool.addPartnerSchool(patschool);
					} catch (Exception e) {
						log.severe(e.getMessage());
						e.printStackTrace();
						throw new ServletException(
								"Error Occurred while uploading the csv file.",
								e);
					}

				}
			}

		} catch (Exception e) {
			log.severe(e.getMessage());
			e.printStackTrace();
			throw new ServletException(
					"Error Occurred while uploading the csv file.", e);
		}

	}
}
